jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build with Maven
      run: mvn -f sidekick -q clean install
    - continue-on-error: true
      if: always()
      name: Analyze Test and/or Coverage Results
      uses: runforesight/foresight-test-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}
        coverage_format: jacoco/xml
        coverage_path: sidekick/*/target/site/jacoco/*.xml
        test_format: junit
        test_framework: junit
        test_path: sidekick/*/target/surefire-reports/**
name: build-maven
on:
  repository_dispatch:
    types: trigger-ga___build.yml
