jobs:
  publish:
    name: Release to Maven Central
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SIDEKICK_DEVOPS_GITHUB_ACCESS_TOKEN }}
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Configure CI Git User
      run: 'git config --global user.email "action@github.com"

        git config --global user.name "GitHub Action"

        '
    - continue-on-error: true
      name: Configure Maven settings.xml
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        servers: "[\n  {\n    \"id\": \"ossrh\",\n    \"username\": \"${{ secrets.SIDEKICK_SONATYPE_NEXUS_USERNAME}}\"\
          ,\n    \"password\": \"${{ secrets.SIDEKICK_SONATYPE_NEXUS_PASSWORD}}\"\n\
          \  }\n]"
    - continue-on-error: true
      name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.SIDEKICK_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.SIDEKICK_GPG_PASSPHRASE}}
    - continue-on-error: true
      if: ${{ github.event.inputs.version_scale == 'minor' }}
      name: Increase Minor Version
      run: mvn -f sidekick build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0-SNAPSHOT
        versions:commit
    - continue-on-error: true
      if: ${{ github.event.inputs.version_scale == 'major' }}
      name: Increase Major Version
      run: mvn -f sidekick build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.nextMajorVersion}.0.0-SNAPSHOT
        versions:commit
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.SIDEKICK_DEVOPS_GITHUB_ACCESS_TOKEN }}
      name: Build and Release with Maven
      run: mvn -f sidekick clean package release:clean release:prepare release:perform
        release:clean --batch-mode -P release
name: release-maven-central
on:
  repository_dispatch:
    types: trigger-ga___release.yml
