jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out source
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SIDEKICK_DEVOPS_GITHUB_ACCESS_TOKEN }}
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Configure CI Git User
      run: 'git config --global user.email "action@github.com"

        git config --global user.name "GitHub Action"

        '
    - continue-on-error: true
      name: Configure Maven settings.xml
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: "[\n  {\n    \"id\": \"sidekick-oss-releases\",\n    \"url\"\
          : \"https://repo.thundra.io/content/repositories/sidekick-oss-releases\"\
          ,\n    \"releases\": {\n      \"enabled\": \"true\"\n    },\n    \"snapshots\"\
          : {\n      \"enabled\": \"false\"\n    }\n  },\n  {\n    \"id\": \"sidekick-oss-snapshots\"\
          ,\n    \"url\": \"https://repo.thundra.io/content/repositories/sidekick-oss-snapshots\"\
          ,\n    \"releases\": {\n      \"enabled\": \"false\"\n    },\n    \"snapshots\"\
          : {\n      \"enabled\": \"true\"\n    }\n  }\n]"
        servers: "[\n  {\n    \"id\": \"sidekick-oss-releases\",\n    \"username\"\
          : \"${{ secrets.SIDEKICK_INTERNAL_REPO_USERNAME  }}\",\n    \"password\"\
          : \"${{ secrets.SIDEKICK_INTERNAL_REPO_PASSWORD  }}\"\n  },\n  {\n    \"\
          id\": \"sidekick-oss-snapshots\",\n    \"username\": \"${{ secrets.SIDEKICK_INTERNAL_REPO_USERNAME\
          \  }}\",\n    \"password\": \"${{ secrets.SIDEKICK_INTERNAL_REPO_PASSWORD\
          \  }}\"\n  }\n]"
    - continue-on-error: true
      name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.SIDEKICK_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.SIDEKICK_GPG_PASSPHRASE}}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.SIDEKICK_DEVOPS_GITHUB_ACCESS_TOKEN }}
      name: Build and Release Snapshot with Maven
      run: mvn -f sidekick -DskipTests=true -q clean package release:clean release:prepare
        release:perform release:clean --batch-mode -P internal-release
name: release-internal-repo
on:
  repository_dispatch:
    types: trigger-ga___release-internal-repo.yml
